
version: "3.7"

services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017